# Generated by Django 4.0.6 on 2022-08-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_researchattending_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResearchField',
            new_name='StudyField',
        ),
        migrations.AlterField(
            model_name='researchattending',
            name='status',
            field=models.CharField(choices=[('AS', 'Assigned'), ('IP', 'InProgress'), ('DR', 'Drop'), ('DO', 'Done')], default='AS', max_length=2),
        ),
    ]
